on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 1
