on: [push]
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
              "id": "upload",
              "username": "${{ env.GITHUB_REPOSITORY_OWNER }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
      - run: mvn --batch-mode --update-snapshots deploy
